import { useState } from "react";
import { useWallet, useConnection } from "@solana/wallet-adapter-react";
import toast from "react-hot-toast";
import { useAegisProgram } from "../hooks/useAegisProgram";
import { useUserVault } from "../hooks/useUserVault";
import {
  deriveVaultPda,
  deriveVaultTokenPda,
  deriveTriggerPda,
} from "../lib/pdas";
import TxButton from "../components/shared/TxButton";
import { PublicKey, SystemProgram } from "@solana/web3.js";
import { TOKEN_PROGRAM_ID, getAssociatedTokenAddress } from "@solana/spl-token";
import BN from "bn.js";
import api from "../lib/api";

// Use the actual USDC mint (or mock one generated by setup script)
const USDC_MINT = new PublicKey(
  import.meta.env.VITE_USDC_MINT || import.meta.env.VITE_MARGINFI_BANK,
);

export default function Deposit() {
  const { publicKey } = useWallet();
  const { connection } = useConnection();
  const program = useAegisProgram();
  const { vault, refreshVault } = useUserVault();

  const handleAirdrop = async () => {
    if (!publicKey) return;
    try {
      const sig = await connection.requestAirdrop(publicKey, 10 * 1e9);
      const { blockhash, lastValidBlockHeight } = await connection.getLatestBlockhash();
      await connection.confirmTransaction({ signature: sig, blockhash, lastValidBlockHeight });
      toast.success("Airdropped 10 SOL!");
    } catch (err: any) {
      toast.error("Devnet airdrop failed or rate limited: " + err.message);
    }
  };

  const handleMintUsdc = async () => {
    if (!publicKey) return;
    try {
      toast.loading("Minting 1,000,000 Mock USDC...", { id: "mint-usdc" });
      const res = await api.post("/api/mint-usdc", { address: publicKey.toBase58() });
      if (!res.data.success) throw new Error(res.data.message);
      toast.success("Minted Mock USDC! You can now deposit.", { id: "mint-usdc" });
    } catch (err: any) {
      toast.error("Mint failed: " + err.message, { id: "mint-usdc" });
    }
  };

  const [amount, setAmount] = useState("");
  const [mode, setMode] = useState<"Defense" | "Offense">("Defense");
  const [defThresh, setDefThresh] = useState("9000"); // 90%
  const [offThresh, setOffThresh] = useState("200"); // 2%

  const vaultExists = !!vault;

  const handleInitVault = async (): Promise<string> => {
    if (!publicKey || !program) throw new Error("Wallet not connected");
    const vaultPda = deriveVaultPda(publicKey);
    const vaultTokenPda = deriveVaultTokenPda(publicKey);

    const tx = await program.methods
      .initializeVault()
      .accounts({
        userVault: vaultPda,
        vaultTokenAccount: vaultTokenPda,
        usdcMint: USDC_MINT,
        owner: publicKey,
        systemProgram: SystemProgram.programId,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .rpc();

    setTimeout(refreshVault, 1000);
    return tx;
  };

  const handleDeposit = async (): Promise<string> => {
    if (!publicKey || !program) throw new Error("Wallet not connected");
    const usdcAmount = Math.floor(parseFloat(amount) * 1_000_000);
    if (isNaN(usdcAmount) || usdcAmount <= 0) throw new Error("Invalid amount");

    const vaultPda = deriveVaultPda(publicKey);
    const vaultTokenPda = deriveVaultTokenPda(publicKey);
    const userAta = await getAssociatedTokenAddress(USDC_MINT, publicKey);

    const tx = await program.methods
      .deposit(new BN(usdcAmount))
      .accounts({
        userVault: vaultPda,
        vaultTokenAccount: vaultTokenPda,
        userTokenAccount: userAta,
        owner: publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .rpc();

    setTimeout(refreshVault, 1000);
    return tx;
  };

  const handleSetTrigger = async (): Promise<string> => {
    if (!publicKey || !program) throw new Error("Wallet not connected");
    const vaultPda = deriveVaultPda(publicKey);
    const triggerPda = deriveTriggerPda(publicKey);
    const modeArg = mode === "Defense" ? { defense: {} } : { offense: {} };

    const tx = await program.methods
      .setTrigger(
        modeArg as any,
        new BN(parseInt(defThresh)),
        new BN(parseInt(offThresh)),
      )
      .accounts({
        triggerConfig: triggerPda,
        userVault: vaultPda,
        owner: publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    return tx;
  };

  if (!publicKey) {
    return (
      <div className="max-w-lg mx-auto px-4 py-20 text-center">
        <p className="text-secondary">Connect your wallet to deposit.</p>
      </div>
    );
  }

  return (
    <div className="max-w-lg mx-auto px-4 py-10 flex flex-col gap-6">
      <div className="bg-surface border border-border rounded-xl p-5 flex justify-between items-center">
        <div>
          <h2 className="text-sm font-medium text-secondary mb-1">
            Localnet Testing
          </h2>
          <p className="text-primary font-medium">Need test funds?</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleAirdrop}
            className="px-4 py-2 rounded-lg bg-border text-primary text-sm hover:bg-border/80 transition-colors"
          >
            Airdrop 10 SOL
          </button>
          <button
            onClick={handleMintUsdc}
            className="px-4 py-2 rounded-lg bg-border text-primary text-sm hover:bg-border/80 transition-colors"
          >
            Mint Mock USDC
          </button>
        </div>
      </div>

      {/* Step 1: Initialize vault if needed */}
      {!vaultExists && (
        <div className="bg-surface border border-border rounded-xl p-5">
          <h2 className="text-sm font-medium text-secondary mb-1">Step 1</h2>
          <p className="text-primary font-medium mb-4">
            Initialize your Aegis vault
          </p>
          <TxButton onClick={handleInitVault}>Create Vault</TxButton>
        </div>
      )}

      {/* Step 2: Deposit */}
      <div
        className={`bg-surface border border-border rounded-xl p-5 ${!vaultExists ? "opacity-40 pointer-events-none" : ""}`}
      >
        <h2 className="text-sm font-medium text-secondary mb-1">
          {!vaultExists ? "Step 2" : "Deposit USDC"}
        </h2>
        <p className="text-primary font-medium mb-4">Deposit USDC into vault</p>
        <div className="flex gap-2">
          <div className="relative flex-1">
            <input
              type="number"
              placeholder="0.00"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              className="
                w-full bg-bg border border-border rounded-lg
                px-4 py-2.5 text-primary font-mono text-sm
                focus:outline-none focus:border-purple/50
                placeholder:text-muted
              "
            />
            <span className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-muted">
              USDC
            </span>
          </div>
          <TxButton onClick={handleDeposit} disabled={!amount}>
            Deposit
          </TxButton>
        </div>
        {vault && (
          <p className="text-xs text-muted mt-2">
            Current balance:{" "}
            {(vault.usdcDeposited.toNumber() / 1_000_000).toFixed(2)} USDC
          </p>
        )}
      </div>

      {/* Step 3: Set trigger */}
      <div
        className={`bg-surface border border-border rounded-xl p-5 ${!vaultExists ? "opacity-40 pointer-events-none" : ""}`}
      >
        <h2 className="text-sm font-medium text-secondary mb-1">
          {!vaultExists ? "Step 3" : "Configure trigger"}
        </h2>
        <p className="text-primary font-medium mb-4">Choose automation mode</p>

        {/* Mode selector */}
        <div className="grid grid-cols-2 gap-3 mb-5">
          {(["Defense", "Offense"] as const).map((m) => (
            <button
              key={m}
              onClick={() => setMode(m)}
              className={`
                p-4 rounded-lg border text-left transition-all
                ${
                  mode === m
                    ? "border-purple bg-purple/10 text-primary"
                    : "border-border text-secondary hover:border-muted"
                }
              `}
            >
              <p className="font-medium text-sm">{m} Mode</p>
              <p className="text-xs text-muted mt-1">
                {m === "Defense"
                  ? "Move funds when MarginFi utilization is too high"
                  : "Move funds to the higher yielding protocol automatically"}
              </p>
            </button>
          ))}
        </div>

        {/* Threshold inputs */}
        <div className="flex flex-col gap-3 mb-5">
          {mode === "Defense" && (
            <div>
              <label className="text-xs text-secondary block mb-1">
                Defense threshold (basis points)
              </label>
              <input
                type="number"
                value={defThresh}
                onChange={(e) => setDefThresh(e.target.value)}
                placeholder="9000"
                className="
                  w-full bg-bg border border-border rounded-lg
                  px-4 py-2.5 text-primary font-mono text-sm
                  focus:outline-none focus:border-purple/50
                "
              />
              <p className="text-xs text-muted mt-1">
                {defThresh
                  ? `Trigger fires when utilization exceeds ${(parseInt(defThresh) / 100).toFixed(2)}%`
                  : ""}
              </p>
            </div>
          )}
          {mode === "Offense" && (
            <div>
              <label className="text-xs text-secondary block mb-1">
                Offense threshold (basis points)
              </label>
              <input
                type="number"
                value={offThresh}
                onChange={(e) => setOffThresh(e.target.value)}
                placeholder="200"
                className="
                  w-full bg-bg border border-border rounded-lg
                  px-4 py-2.5 text-primary font-mono text-sm
                  focus:outline-none focus:border-purple/50
                "
              />
              <p className="text-xs text-muted mt-1">
                {offThresh
                  ? `Trigger fires when APY difference exceeds ${(parseInt(offThresh) / 100).toFixed(2)}%`
                  : ""}
              </p>
            </div>
          )}
        </div>

        <TxButton onClick={handleSetTrigger}>Arm Trigger</TxButton>
      </div>
    </div>
  );
}
