import { Connection, Keypair } from "@solana/web3.js";
import * as anchor from "@coral-xyz/anchor";
import * as fs from "fs";
import * as path from "path";
import dotenv from "dotenv";

dotenv.config();

// Load IDL generated by anchor build
// Ensure aegis/anchor/target/idl/aegis.json is copied to aegis/server/idl/aegis.json
// or read directly from the anchor folder if running locally
let idlPath = path.resolve(__dirname, "../idl/aegis.json");
if (!fs.existsSync(idlPath)) {
  idlPath = path.resolve(__dirname, "../../anchor/target/idl/aegis.json");
}

const idlRaw = fs.readFileSync(idlPath, "utf8");
export const IDL = JSON.parse(idlRaw);

export const connection = new Connection(
  process.env.RPC_URL || "http://127.0.0.1:8899",
  "confirmed",
);

// Load crank keypair from file
const keypairPath = process.env.CRANK_KEYPAIR_PATH || "./crank-keypair.json";
let crankKeypairData: number[];
try {
  crankKeypairData = JSON.parse(fs.readFileSync(keypairPath, "utf8"));
} catch (err: any) {
  console.warn(
    `Could not load crank keypair at ${keypairPath}. Using a random keypair for now.`,
  );
  crankKeypairData = Array.from(Keypair.generate().secretKey);
}
export const crankKeypair = Keypair.fromSecretKey(
  new Uint8Array(crankKeypairData),
);

// Build Anchor provider and program
export const wallet = new anchor.Wallet(crankKeypair);
export const provider = new anchor.AnchorProvider(connection, wallet, {
  commitment: "confirmed",
});
anchor.setProvider(provider);

export const program = new anchor.Program(IDL, provider);
